<a href="https://colab.research.google.com/github/marioespinosa-sys/MatBach_Python/blob/main/Viernes28uno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import auth
from pydrive.drive import GoogleDrive
from pydrive.auth import GoogleAuth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive= GoogleDrive(gauth)

# El ID es el número que aparece al compartir el archivo
myfile = drive.CreateFile({'id': '1rNlA6odqMfMvJxzwiEkxpg8hOZBs3ERa'})
myfile.GetContentFile('datos1.txt')

import pandas as pd
frm = pd.read_csv('datos1.txt', header=None)
print(frm.head())
print(frm.tail())

    0    1     2
0   1  1.3   0.6
1   2  2.1   0.7
2   3  4.8   0.8
3   4  3.3   0.9
4  56  3.3  21.0
     0      1      2
2    3    4.8    0.8
3    4    3.3    0.9
4   56    3.3   21.0
5  333  555.0  666.0
6   54   67.0   78.0


In [ ]:
import numpy as np
datosF = np.loadtxt('datos1.txt', delimiter = ",")
print(datosF)

print(datosF[:,0])

[[1.00e+00 1.30e+00 6.00e-01]
 [2.00e+00 2.10e+00 7.00e-01]
 [3.00e+00 4.80e+00 8.00e-01]
 [4.00e+00 3.30e+00 9.00e-01]
 [5.60e+01 3.30e+00 2.10e+01]
 [3.33e+02 5.55e+02 6.66e+02]
 [5.40e+01 6.70e+01 7.80e+01]]
[  1.   2.   3.   4.  56. 333.  54.]
